CREATE TABLE IF NOT EXISTS BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  VALOR_CENTAVOS BIGINT NOT NULL,
  ATIVO BOOLEAN DEFAULT TRUE,
  VERSION BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS TRANSFERENCIA (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ORIGEM_BENEFICIO_ID BIGINT NOT NULL REFERENCES BENEFICIO(ID),
  DESTINO_BENEFICIO_ID BIGINT NOT NULL REFERENCES BENEFICIO(ID),
  VALOR_CENTAVOS BIGINT NOT NULL,
  CRIADA_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CK_TRANSFERENCIA_VALOR_POSITIVO CHECK (VALOR_CENTAVOS > 0),
  CONSTRAINT CK_TRANSFERENCIA_ORIGEM_DESTINO CHECK (ORIGEM_BENEFICIO_ID <> DESTINO_BENEFICIO_ID)
);

CREATE INDEX IF NOT EXISTS IX_TRANSFERENCIA_ORIGEM ON TRANSFERENCIA (ORIGEM_BENEFICIO_ID);
CREATE INDEX IF NOT EXISTS IX_TRANSFERENCIA_DESTINO ON TRANSFERENCIA (DESTINO_BENEFICIO_ID);
